-- Outstanding Material schema-only installation (fresh tables only)
-- Prerequisite: database/sql/00_preflight.sql returned PASS for both requirements.
-- This file deliberately contains no business data, no migration ledger entries,
-- no INSERT, UPDATE, DELETE, or DROP statements.
-- Do not run this script when either Outstanding Material table already exists.

CREATE TABLE `outstanding_material_invoices` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `supplier` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `number_invoice` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `invoice_identity_key` char(64) COLLATE utf8mb4_unicode_ci NOT NULL,
  `packing_list_path` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `mtc_path` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `document_review_required` tinyint(1) NOT NULL DEFAULT '0',
  `created_by` bigint unsigned DEFAULT NULL,
  `updated_by` bigint unsigned DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `outstanding_material_invoices_invoice_identity_key_unique` (`invoice_identity_key`),
  KEY `outstanding_material_invoices_created_by_foreign` (`created_by`),
  KEY `outstanding_material_invoices_updated_by_foreign` (`updated_by`),
  KEY `outstanding_material_invoices_supplier_number_invoice_index` (`supplier`,`number_invoice`),
  CONSTRAINT `outstanding_material_invoices_created_by_foreign` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `outstanding_material_invoices_updated_by_foreign` FOREIGN KEY (`updated_by`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `outstanding_materials` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `invoice_id` bigint unsigned DEFAULT NULL,
  `supplier` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `type` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `thickness` decimal(15,2) DEFAULT NULL,
  `width` decimal(15,2) DEFAULT NULL,
  `diameter` decimal(15,2) DEFAULT NULL,
  `length` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `qty_pcs` decimal(15,2) DEFAULT NULL,
  `est_qty_kg` decimal(15,2) DEFAULT NULL,
  `number_invoice` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `invoice_identity_key` char(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `status` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `estimasi_eta_port` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `estimasi_eta_warehouse` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `estimasi_bulan_eta` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `keterangan` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `estimasi_delay_eta_port` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `estimasi_delay_eta_warehouse` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `attachment_path` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `packing_list_path` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `mtc_path` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_by` bigint unsigned DEFAULT NULL,
  `updated_by` bigint unsigned DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `deleted_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `outstanding_materials_created_by_foreign` (`created_by`),
  KEY `outstanding_materials_updated_by_foreign` (`updated_by`),
  KEY `outstanding_materials_supplier_index` (`supplier`),
  KEY `outstanding_materials_type_index` (`type`),
  KEY `outstanding_materials_status_index` (`status`),
  KEY `outstanding_materials_keterangan_index` (`keterangan`),
  KEY `outstanding_materials_estimasi_bulan_eta_index` (`estimasi_bulan_eta`),
  KEY `outstanding_materials_estimasi_eta_port_index` (`estimasi_eta_port`),
  KEY `outstanding_materials_estimasi_eta_warehouse_index` (`estimasi_eta_warehouse`),
  KEY `outstanding_materials_invoice_identity_idx` (`invoice_identity_key`),
  KEY `outstanding_materials_invoice_id_index` (`invoice_id`),
  CONSTRAINT `outstanding_materials_created_by_foreign` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `outstanding_materials_invoice_id_foreign` FOREIGN KEY (`invoice_id`) REFERENCES `outstanding_material_invoices` (`id`) ON DELETE SET NULL,
  CONSTRAINT `outstanding_materials_updated_by_foreign` FOREIGN KEY (`updated_by`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;