@extends('warehouse.layout')

@push('styles')
    @vite('resources/css/warehouse/location-shipments.css')
@endpush

@section('warehouse-content')
    <div class="warehouse-shipment-page" aria-labelledby="warehouse-shipment-validate-title">
        <x-warehouse.page-header title="Serah Terima & Validasi" subtitle="Bandingkan barang fisik dengan data pengiriman. Hasil Tidak Sesuai tidak memindahkan saldo."><a class="btn btn-outline-secondary" href="{{ route('warehouse.location-shipments.show', $shipment) }}">Kembali ke Detail</a></x-warehouse.page-header>
        @if ($errors->any())<div class="alert alert-danger" role="alert"><strong>Validasi belum dapat disimpan.</strong><ul class="mb-0 mt-2">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
        <div class="warehouse-shipment-validation-grid"><section class="warehouse-panel"><div class="warehouse-panel-header"><div><h2>Data Pengiriman</h2><p>Data ini read-only dari Pengirim.</p></div></div><div class="warehouse-panel-body"><dl class="warehouse-shipment-readonly"><div><dt>Nomor Pengiriman</dt><dd class="font-monospace">{{ $shipment->shipment_number }}</dd></div><div><dt>Pengirim</dt><dd>{{ $shipment->sender_name_snapshot }}</dd></div><div><dt>Asal → Tujuan</dt><dd>{{ $shipment->from_location }} → {{ $shipment->to_location }}</dd></div><div><dt>Barang</dt><dd>{{ $shipment->consumable?->item_name }} ({{ $shipment->consumable?->item_code }})</dd></div><div><dt>Condition</dt><dd>{{ $shipment->item_condition?->label() }}</dd></div><div><dt>Qty Dikirim</dt><dd><strong>{{ \App\Services\Warehouse\WarehouseQuantity::display($shipment->quantity_sent) }} {{ $shipment->consumable?->unit }}</strong></dd></div><div><dt>Catatan Pengirim</dt><dd>{{ $shipment->sender_notes ?: '—' }}</dd></div></dl></div></section>
            <form class="warehouse-panel warehouse-validation-form" method="POST" action="{{ route('warehouse.location-shipments.validate', $shipment) }}"><div class="warehouse-panel-header"><div><h2>Hasil Pengecekan Fisik</h2><p>Validator ditentukan saat serah terima, bukan oleh Pengirim.</p></div></div><div class="warehouse-panel-body warehouse-shipment-form-grid"><div class="warehouse-form-field"><label class="form-label warehouse-required" for="received-quantity">Qty diterima aktual</label><input class="form-control" id="received-quantity" name="received_quantity" type="number" min="0.001" step="0.001" value="{{ old('received_quantity', $shipment->quantity_sent) }}" required></div><div class="warehouse-form-field"><label class="form-label warehouse-required" for="received-condition">Condition diterima</label><select class="form-select" id="received-condition" name="received_condition" required><option value="NEW" @selected(old('received_condition', $shipment->item_condition?->value) === 'NEW')>Baru (NEW)</option><option value="USED" @selected(old('received_condition', $shipment->item_condition?->value) === 'USED')>Bekas (USED)</option></select></div><div class="warehouse-form-field warehouse-detail-full"><label class="form-label" for="received-item-barcode">Scan barcode barang diterima <span class="warehouse-muted">(opsional)</span></label><input class="form-control font-monospace" id="received-item-barcode" name="received_item_barcode" value="{{ old('received_item_barcode') }}" inputmode="text" autocomplete="off"></div><div class="warehouse-form-field warehouse-detail-full"><label class="form-label warehouse-required" for="validator-code">NPK Validator</label><input class="form-control font-monospace" id="validator-code" name="validator_code" value="{{ old('validator_code') }}" inputmode="numeric" autocomplete="off" required><div class="warehouse-help">Scan NPK user yang menerima barang. Pengirim sendiri tidak dapat menjadi Validator.</div></div><div class="warehouse-form-field warehouse-detail-full"><label class="form-label" for="validation-notes">Catatan Validasi</label><textarea class="form-control" id="validation-notes" name="validation_notes" rows="4" maxlength="2000">{{ old('validation_notes') }}</textarea><div class="warehouse-help">Wajib diisi bila jumlah, condition, atau item fisik Tidak Sesuai.</div></div></div><div class="card-footer d-flex flex-wrap gap-2"><input type="hidden" name="idempotency_key" value="{{ old('idempotency_key', (string) str()->uuid()) }}"><button class="btn btn-primary" type="submit">Simpan Hasil Validasi</button><a class="btn btn-outline-secondary" href="{{ route('warehouse.location-shipments.show', $shipment) }}">Batal</a></div></form>
        </div>
    </div>
@endsection
