<?php

return [
    'sections' => [
        [
            'label' => 'Profil',
            'route' => 'profile',
        ],
        [
            'label' => 'Kelola Data',
            'permissions' => [
                'role_ids' => [1],
            ],
            'children' => [
                [
                    'label' => 'Akun Users',
                    'route' => 'dashboardusers',
                ],
                [
                    'label' => 'Customers',
                    'route' => 'dashboardcustomers',
                ],
                [
                    'label' => 'Layout',
                    'route' => 'layout-editor.edit',
                ],
            ],
        ],
        [
            'label' => 'Dashboard',
            'children' => [
                [
                    'label' => 'Maintenance',
                    'route' => 'dashboardMaintenance',
                    'permissions' => [
                        'usernames' => [
                            'ADMINSTRATOR',
                            'ANDI SIMPONI',
                            'MUGI PRAMONO',
                            'RANGGA FADILLAH',
                            'VITRI HANDAYANI',
                            'ADHI PRASETIYO',
                            'AHMAD RIDWAN',
                            'ANDIK TOTOK SISWOYO',
                            'ARY RODJO PRASETYO',
                            'DANIA ISNAWATI',
                            'DINA NIMAS AYU NAWAWULAN PRIHANTINI',
                            'DWI KUNTORO',
                            'HARDI SAPUTRA',
                            'HUSEIN ABDULLAH',
                            'ILHAM CHOLID',
                            'JESSICA PAUNE',
                            'JUN JOHAMIN PD',
                            'KUSTIONO',
                            'LINA UNIARSIH',
                            'M. RIDWAN GUNAWAN',
                            'MARTINUS CAHYO RAHASTO',
                            'MUHAMMAD MAHBUB',
                            'NUR DWITA SURA WIJAYA',
                            'PUTRI ANINDIA',
                            'RAGIL ISHA RAHMANTO',
                            'RICHARDUS CHRISTIAN',
                            'RISFAN FAISAL',
                            'SENDY PRABOWO',
                            'SITI MARIA ULFA',
                            'WULYO EKO PRASETYO',
                            'YAN WELEM MANGINSELA',
                            'YULMAI RIDO WINANDA',
                            'YUNASIS PALGUNADI',
                            'ABDUR RAHMAN AL FAAIZ',
                            'SONY STIAWAN',
                            'HERLIANA',
                        ],
                    ],
                ],
                [
                    'label' => 'Handling Klaim dan Komplain',
                    'route' => 'dshandling',
                    'permissions' => [
                        'usernames' => [
                            'ADMINSTRATOR',
                            'ANDI SIMPONI',
                            'MUGI PRAMONO',
                            'RANGGA FADILLAH',
                            'VITRI HANDAYANI',
                            'ADHI PRASETIYO',
                            'AHMAD RIDWAN',
                            'ANDIK TOTOK SISWOYO',
                            'ARY RODJO PRASETYO',
                            'DANIA ISNAWATI',
                            'DINA NIMAS AYU NAWAWULAN PRIHANTINI',
                            'DWI KUNTORO',
                            'HARDI SAPUTRA',
                            'HUSEIN ABDULLAH',
                            'ILHAM CHOLID',
                            'JESSICA PAUNE',
                            'JUN JOHAMIN PD',
                            'KUSTIONO',
                            'LINA UNIARSIH',
                            'M. RIDWAN GUNAWAN',
                            'MARTINUS CAHYO RAHASTO',
                            'MUHAMMAD MAHBUB',
                            'NUR DWITA SURA WIJAYA',
                            'PUTRI ANINDIA',
                            'RAGIL ISHA RAHMANTO',
                            'RICHARDUS CHRISTIAN',
                            'RISFAN FAISAL',
                            'SENDY PRABOWO',
                            'SITI MARIA ULFA',
                            'WULYO EKO PRASETYO',
                            'YAN WELEM MANGINSELA',
                            'YULMAI RIDO WINANDA',
                            'YUNASIS PALGUNADI',
                            'ABDUR RAHMAN AL FAAIZ',
                            'SONY STIAWAN',
                            'HERLIANA',
                        ],
                    ],
                ],
                [
                    'label' => 'People Development',
                    'route' => 'dsCompetency',
                    'permissions' => [
                        'usernames' => [
                            'ADMINSTRATOR',
                            'ANDI SIMPONI',
                            'MUGI PRAMONO',
                            'RANGGA FADILLAH',
                            'VITRI HANDAYANI',
                            'ADHI PRASETIYO',
                            'AHMAD RIDWAN',
                            'ANDIK TOTOK SISWOYO',
                            'ARY RODJO PRASETYO',
                            'DANIA ISNAWATI',
                            'DINA NIMAS AYU NAWAWULAN PRIHANTINI',
                            'DWI KUNTORO',
                            'HARDI SAPUTRA',
                            'HUSEIN ABDULLAH',
                            'ILHAM CHOLID',
                            'JESSICA PAUNE',
                            'JUN JOHAMIN PD',
                            'KUSTIONO',
                            'LINA UNIARSIH',
                            'M. RIDWAN GUNAWAN',
                            'MARTINUS CAHYO RAHASTO',
                            'MUHAMMAD MAHBUB',
                            'NUR DWITA SURA WIJAYA',
                            'PUTRI ANINDIA',
                            'RAGIL ISHA RAHMANTO',
                            'RICHARDUS CHRISTIAN',
                            'RISFAN FAISAL',
                            'SENDY PRABOWO',
                            'SITI MARIA ULFA',
                            'WULYO EKO PRASETYO',
                            'YAN WELEM MANGINSELA',
                            'YULMAI RIDO WINANDA',
                            'YUNASIS PALGUNADI',
                            'ABDUR RAHMAN AL FAAIZ',
                            'SONY STIAWAN',
                            'HERLIANA',
                        ],
                    ],
                ],
                [
                    'label' => 'Sumbang Saran',
                    'route' => 'dashboardSS',
                    'permissions' => [
                        'usernames' => [
                            'ADMINSTRATOR',
                            'AFILIANDI',
                            'AGUNG PANGESTU YUSUF',
                            'AGUS PRIYANTO',
                            'AGUS ROSIDIN',
                            'ANDI SANTOSO',
                            'ANDI SIMPONI',
                            'ARRY SOEBHEKTI',
                            'AWING',
                            'DASUKI',
                            'DEDY SETIAWAN',
                            'DIAMAN DARMAWINATA',
                            'ELI HANDOYO',
                            'FAIZAL AFDAU',
                            'FATUL MUKMIN',
                            'HAERUL IKHSAN',
                            'HENDRIO',
                            'JAKA RARA SUKMA',
                            'JAKARIA',
                            'KARYA WIJAYA',
                            'LUKMAN AHMAD',
                            'MAMIK ABIDIN',
                            'MEDI KRISNANTO',
                            'MIFTAKHUROHMAN',
                            'MUGI PRAMONO',
                            'NUR SUPRIYANTO',
                            'NURSAID',
                            'NURSALIM',
                            'R.WAWAN HIMAWAN',
                            'RAHMAT NUGROHO',
                            'RANGGA FADILLAH',
                            'RIZKY ANDREA RAHMAWAN',
                            'RUKMAN',
                            'RUSITO',
                            'SABAR WASIRAN',
                            'SEPTIADI PRATOMO',
                            'SUDIYATNO',
                            'UMAR HADI',
                            'VITRI HANDAYANI',
                            'YANUARDIN SALEH SIREGAR',
                            'YUSUF SYAFAAT',
                            'ADHI PRASETIYO',
                            'AHMAD RIDWAN',
                            'ANDIK TOTOK SISWOYO',
                            'ARY RODJO PRASETYO',
                            'AVI SHENNA',
                            'BANGUN SUTOPO',
                            'CECEP ISKANDAR',
                            'DANIA ISNAWATI',
                            'DINA NIMAS AYU NAWAWULAN PRIHANTINI',
                            'DWI KUNTORO',
                            'FIKRI SYAHBANA',
                            'FRISILIA CLAUDIA HUTAMA',
                            'GUNAWAN',
                            'HARDI SAPUTRA',
                            'HARRY SUPRIYADI',
                            'HERLIANA',
                            'HERY HERMAWAN',
                            'HUSEIN ABDULLAH',
                            'ILHAM CHOLID',
                            'ILHAM SETIA DARMA',
                            'IMAM PRASETYO',
                            'IMAM SOPYAN',
                            'JEFRY WASTON E',
                            'JESSICA PAUNE',
                            'JONI SETIAWAN',
                            'JUN JOHAMIN PD',
                            'KUSTIONO',
                            'LINA UNIARSIH',
                            'M. RIDWAN GUNAWAN',
                            'MARTINUS CAHYO RAHASTO',
                            'MOCHAMMAD ANDRIANSYAH',
                            'MOHAMMAD FATKHURROHMAN',
                            'MUHAMMAD DINAR FARISI',
                            'MUHAMMAD MAHBUB',
                            'NUR DWITA SURA WIJAYA',
                            'PUTRI ANINDIA',
                            'RAGIL ISHA RAHMANTO',
                            'RIADUS SOLIHIN',
                            'RICHARDUS CHRISTIAN',
                            'RISFAN FAISAL',
                            'RUSLAN M.ALI',
                            'SENDY PRABOWO',
                            'SETIYAWAN',
                            'SITI MARIA ULFA',
                            'SUKIMIN',
                            'WULYO EKO PRASETYO',
                            'YAN WELEM MANGINSELA',
                            'YUDHI PRASETYO RAHMAWANTO',
                            'YULMAI RIDO WINANDA',
                            'YUNASIS PALGUNADI',
                            'ZAENAL ARIFIN',
                            'ABDUR RAHMAN AL FAAIZ',
                            'YAN WALEM MANGINSELA',
                            'VIVIAN ANGELIKA',
                            'SONY STIAWAN',
                            'FAJAR BAGASKARA',
                        ],
                    ],
                ],
                [
                    'label' => 'Knowledge Management',
                    'route' => 'dsKnowlege',
                    'permissions' => [
                        'usernames' => [
                            'ADMINSTRATOR',
                            'AFILIANDI',
                            'AGUNG PANGESTU YUSUF',
                            'AGUS PRIYANTO',
                            'AGUS ROSIDIN',
                            'ANDI SANTOSO',
                            'ANDI SIMPONI',
                            'ARRY SOEBHEKTI',
                            'AWING',
                            'DASUKI',
                            'DEDY SETIAWAN',
                            'DIAMAN DARMAWINATA',
                            'ELI HANDOYO',
                            'FAIZAL AFDAU',
                            'FATUL MUKMIN',
                            'HAERUL IKHSAN',
                            'HENDRIO',
                            'JAKA RARA SUKMA',
                            'JAKARIA',
                            'KARYA WIJAYA',
                            'LUKMAN AHMAD',
                            'MAMIK ABIDIN',
                            'MEDI KRISNANTO',
                            'MIFTAKHUROHMAN',
                            'MUGI PRAMONO',
                            'NUR SUPRIYANTO',
                            'NURSAID',
                            'NURSALIM',
                            'R.WAWAN HIMAWAN',
                            'RAHMAT NUGROHO',
                            'RANGGA FADILLAH',
                            'RIZKY ANDREA RAHMAWAN',
                            'RUKMAN',
                            'RUSITO',
                            'SABAR WASIRAN',
                            'SEPTIADI PRATOMO',
                            'SUDIYATNO',
                            'UMAR HADI',
                            'VITRI HANDAYANI',
                            'YANUARDIN SALEH SIREGAR',
                            'YUSUF SYAFAAT',
                            'ADHI PRASETIYO',
                            'AHMAD RIDWAN',
                            'ANDIK TOTOK SISWOYO',
                            'ARY RODJO PRASETYO',
                            'AVI SHENNA',
                            'BANGUN SUTOPO',
                            'CECEP ISKANDAR',
                            'DANIA ISNAWATI',
                            'DINA NIMAS AYU NAWAWULAN PRIHANTINI',
                            'DWI KUNTORO',
                            'FIKRI SYAHBANA',
                            'FRISILIA CLAUDIA HUTAMA',
                            'GUNAWAN',
                            'HARDI SAPUTRA',
                            'HARRY SUPRIYADI',
                            'HERLIANA',
                            'HERY HERMAWAN',
                            'HUSEIN ABDULLAH',
                            'ILHAM CHOLID',
                            'ILHAM SETIA DARMA',
                            'IMAM PRASETYO',
                            'IMAM SOPYAN',
                            'JEFRY WASTON E',
                            'JESSICA PAUNE',
                            'JONI SETIAWAN',
                            'JUN JOHAMIN PD',
                            'KUSTIONO',
                            'LINA UNIARSIH',
                            'M. RIDWAN GUNAWAN',
                            'MARTINUS CAHYO RAHASTO',
                            'MOCHAMMAD ANDRIANSYAH',
                            'MOHAMMAD FATKHURROHMAN',
                            'MUHAMMAD DINAR FARISI',
                            'MUHAMMAD MAHBUB',
                            'NUR DWITA SURA WIJAYA',
                            'PUTRI ANINDIA',
                            'RAGIL ISHA RAHMANTO',
                            'RIADUS SOLIHIN',
                            'RICHARDUS CHRISTIAN',
                            'RISFAN FAISAL',
                            'RUSLAN M.ALI',
                            'SENDY PRABOWO',
                            'SETIYAWAN',
                            'SITI MARIA ULFA',
                            'SUKIMIN',
                            'WULYO EKO PRASETYO',
                            'YAN WELEM MANGINSELA',
                            'YUDHI PRASETYO RAHMAWANTO',
                            'YULMAI RIDO WINANDA',
                            'YUNASIS PALGUNADI',
                            'ZAENAL ARIFIN',
                            'ABDUR RAHMAN AL FAAIZ',
                            'YAN WALEM MANGINSELA',
                            'VIVIAN ANGELIKA',
                            'SONY STIAWAN',
                            'FAJAR BAGASKARA',
                        ],
                    ],
                ],
                [
                    'label' => 'Pengajuan Barang',
                    'route' => 'dashboardFPB',
                    'permissions' => [
                        'usernames' => [
                            'ADMINSTRATOR',
                            'MEDI KRISNANTO',
                            'JESSICA PAUNE',
                            'MARTINUS CAHYO RAHASTO',
                            'VIVIAN ANGELIKA',
                        ],
                    ],
                ],
                [
                    'label' => 'Dashboard TCPD',
                    'route' => 'dashboardTCPD',
                ],
            ],
        ],
        [
            'label' => 'Sales',
            'children' => [
                [
                    'label' => 'Form Permintaan Perbaikan',
                    'children' => [
                        [
                            'label' => 'Data Form Perbaikan',
                            'route' => 'sales.index',
                            'permissions' => [
                                'usernames' => [
                                    'ADMINSTRATOR',
                                    'MAMIK ABIDIN',
                                    'MUGI PRAMONO',
                                    'RANGGA FADILLAH',
                                    'RUSITO',
                                    'SUDIYATNO',
                                    'ARY RODJO PRASETYO',
                                    'BANGUN SUTOPO',
                                    'JESSICA PAUNE',
                                    'RAGIL ISHA RAHMANTO',
                                    'ZAENAL ARIFIN',
                                    'ABDUR RAHMAN AL FAAIZ',
                                    'SONY STIAWAN',
                                ],
                            ],
                        ],
                        [
                            'label' => 'Riwayat Form Perbaikan',
                            'route' => 'fpps.history',
                            'permissions' => [
                                'usernames' => [
                                    'ADMINSTRATOR',
                                    'MAMIK ABIDIN',
                                    'MUGI PRAMONO',
                                    'RANGGA FADILLAH',
                                    'RUSITO',
                                    'SUDIYATNO',
                                    'ARY RODJO PRASETYO',
                                    'BANGUN SUTOPO',
                                    'JESSICA PAUNE',
                                    'RAGIL ISHA RAHMANTO',
                                    'ZAENAL ARIFIN',
                                    'ABDUR RAHMAN AL FAAIZ',
                                ],
                            ],
                        ],
                    ],
                ],
                [
                    'label' => 'Handling Klaim dan Komplain',
                    'children' => [
                        [
                            'label' => 'Form Pengajuan Klaim/Komplain',
                            'route' => 'index',
                            'permissions' => [
                                'usernames' => [
                                    'ADMINSTRATOR',
                                    'MUGI PRAMONO',
                                    'RANGGA FADILLAH',
                                    'ADHI PRASETIYO',
                                    'AHMAD RIDWAN',
                                    'ANDIK TOTOK SISWOYO',
                                    'ARY RODJO PRASETYO',
                                    'AVI SHENNA',
                                    'DANIA ISNAWATI',
                                    'DINA NIMAS AYU NAWAWULAN PRIHANTINI',
                                    'DWI KUNTORO',
                                    'FIKRI SYAHBANA',
                                    'GUNAWAN',
                                    'HARDI SAPUTRA',
                                    'HUSEIN ABDULLAH',
                                    'ILHAM CHOLID',
                                    'JESSICA PAUNE',
                                    'JONI SETIAWAN',
                                    'JUN JOHAMIN PD',
                                    'LINA UNIARSIH',
                                    'M. RIDWAN GUNAWAN',
                                    'MARTINUS CAHYO RAHASTO',
                                    'MOHAMMAD FATKHURROHMAN',
                                    'NUR DWITA SURA WIJAYA',
                                    'PUTRI ANINDIA',
                                    'RIADUS SOLIHIN',
                                    'RICHARDUS CHRISTIAN',
                                    'RISFAN FAISAL',
                                    'RUSLAN M.ALI',
                                    'SENDY PRABOWO',
                                    'SUKIMIN',
                                    'WULYO EKO PRASETYO',
                                    'YAN WELEM MANGINSELA',
                                    'YUDHI PRASETYO RAHMAWANTO',
                                    'YULMAI RIDO WINANDA',
                                    'YUNASIS PALGUNADI',
                                    'SONY STIAWAN',
                                ],
                            ],
                        ],
                        [
                            'label' => 'Riwayat Klaim/Komplain',
                            'route' => 'showHistoryCLaimComplain',
                            'permissions' => [
                                'usernames' => [
                                    'ADMINSTRATOR',
                                    'ADHI PRASETIYO',
                                    'AHMAD RIDWAN',
                                    'ANDIK TOTOK SISWOYO',
                                    'DANIA ISNAWATI',
                                    'DINA NIMAS AYU NAWAWULAN PRIHANTINI',
                                    'DWI KUNTORO',
                                    'GUNAWAN',
                                    'HUSEIN ABDULLAH',
                                    'ILHAM CHOLID',
                                    'JESSICA PAUNE',
                                    'JUN JOHAMIN PD',
                                    'LINA UNIARSIH',
                                    'M. RIDWAN GUNAWAN',
                                    'MARTINUS CAHYO RAHASTO',
                                    'NUR DWITA SURA WIJAYA',
                                    'PUTRI ANINDIA',
                                    'RICHARDUS CHRISTIAN',
                                    'RISFAN FAISAL',
                                    'SENDY PRABOWO',
                                    'WULYO EKO PRASETYO',
                                    'YAN WELEM MANGINSELA',
                                    'YUDHI PRASETYO RAHMAWANTO',
                                    'YULMAI RIDO WINANDA',
                                    'YUNASIS PALGUNADI',
                                    'SONY STIAWAN',
                                ],
                            ],
                        ],
                        [
                            'label' => 'Jadwal Kunjungan',
                            'route' => 'scheduleVisit',
                            'permissions' => [
                                'usernames' => [
                                    'ADMINSTRATOR',
                                    'ADHI PRASETIYO',
                                    'AHMAD RIDWAN',
                                    'ANDIK TOTOK SISWOYO',
                                    'DANIA ISNAWATI',
                                    'DINA NIMAS AYU NAWAWULAN PRIHANTINI',
                                    'DWI KUNTORO',
                                    'GUNAWAN',
                                    'HUSEIN ABDULLAH',
                                    'ILHAM CHOLID',
                                    'JESSICA PAUNE',
                                    'JUN JOHAMIN PD',
                                    'LINA UNIARSIH',
                                    'M. RIDWAN GUNAWAN',
                                    'MARTINUS CAHYO RAHASTO',
                                    'NUR DWITA SURA WIJAYA',
                                    'PUTRI ANINDIA',
                                    'RICHARDUS CHRISTIAN',
                                    'RISFAN FAISAL',
                                    'SENDY PRABOWO',
                                    'WULYO EKO PRASETYO',
                                    'YAN WELEM MANGINSELA',
                                    'YUDHI PRASETYO RAHMAWANTO',
                                    'YULMAI RIDO WINANDA',
                                    'YUNASIS PALGUNADI',
                                    'SONY STIAWAN',
                                ],
                            ],
                        ],
                    ],
                ],
                [
                    'label' => 'Inquiry Status',
                    'permissions' => [
                        'usernames' => [
                            'ADMINSTRATOR',
                            'ADHI PRASETIYO',
                            'AHMAD RIDWAN',
                            'ANDIK TOTOK SISWOYO',
                            'DANIA ISNAWATI',
                            'DINA NIMAS AYU NAWAWULAN PRIHANTINI',
                            'DWI KUNTORO',
                            'GUNAWAN',
                            'HUSEIN ABDULLAH',
                            'ILHAM CHOLID',
                            'JESSICA PAUNE',
                            'JUN JOHAMIN PD',
                            'LINA UNIARSIH',
                            'M. RIDWAN GUNAWAN',
                            'MARTINUS CAHYO RAHASTO',
                            'NUR DWITA SURA WIJAYA',
                            'PUTRI ANINDIA',
                            'RICHARDUS CHRISTIAN',
                            'RISFAN FAISAL',
                            'SENDY PRABOWO',
                            'WULYO EKO PRASETYO',
                            'YAN WELEM MANGINSELA',
                            'YUDHI PRASETYO RAHMAWANTO',
                            'YULMAI RIDO WINANDA',
                            'YUNASIS PALGUNADI',
                            'SONY STIAWAN',
                        ],
                    ],
                    'children' => [
                        [
                            'label' => 'Form Inquiry Material',
                            'route' => 'createinquiry',
                        ],
                    ],
                ],
                [
                    'label' => 'Custom Request',
                    'children' => [
                        [
                            'label' => 'Custom Request',
                            'route' => 'showCustomRequest',
                        ],
                        [
                            'label' => 'Persetujuan Marketing',
                            'route' => 'showApproveMarketing',
                        ],
                        [
                            'label' => 'Persetujuan Finance',
                            'route' => 'showApproveFinance',
                        ],
                    ],
                ],
            ],
        ],
        [
            'label' => 'Productions',
            'children' => [
                [
                    'label' => 'Form Permintaan Perbaikan',
                    'route' => 'fpps.index',
                    'permissions' => [
                        'usernames' => [
                            'ADMINSTRATOR',
                            'MAMIK ABIDIN',
                            'MUGI PRAMONO',
                            'RANGGA FADILLAH',
                            'RUSITO',
                            'SUDIYATNO',
                            'ARY RODJO PRASETYO',
                            'BANGUN SUTOPO',
                            'JESSICA PAUNE',
                            'RAGIL ISHA RAHMANTO',
                            'ZAENAL ARIFIN',
                            'ABDUR RAHMAN AL FAAIZ',
                            'SONY STIAWAN',
                        ],
                    ],
                ],
                [
                    'label' => 'Riwayat Permintaan Perbaikan',
                    'route' => 'fpps.history',
                    'permissions' => [
                        'usernames' => [
                            'ADMINSTRATOR',
                            'MAMIK ABIDIN',
                            'MUGI PRAMONO',
                            'RANGGA FADILLAH',
                            'RUSITO',
                            'SUDIYATNO',
                            'ARY RODJO PRASETYO',
                            'BANGUN SUTOPO',
                            'JESSICA PAUNE',
                            'RAGIL ISHA RAHMANTO',
                            'ZAENAL ARIFIN',
                            'ABDUR RAHMAN AL FAAIZ',
                        ],
                    ],
                ],
                [
                    'label' => 'Bagian Maintenance',
                    'children' => [
                        [
                            'label' => 'Kelola DMI',
                            'route' => 'dashboardmesins',
                            'permissions' => [
                                'usernames' => [
                                    'ADMINSTRATOR',
                                    'MUGI PRAMONO',
                                    'VITRI HANDAYANI',
                                    'ANDIK TOTOK SISWOYO',
                                    'ARY RODJO PRASETYO',
                                    'HARDI SAPUTRA',
                                    'JESSICA PAUNE',
                                    'MARTINUS CAHYO RAHASTO',
                                    'SITI MARIA ULFA',
                                    'YULMAI RIDO WINANDA',
                                ],
                            ],
                        ],
                        [
                            'label' => 'Persetujuan FPP',
                            'route' => 'deptmtce.index',
                            'permissions' => [
                                'usernames' => [
                                    'ADMINSTRATOR',
                                    'MUGI PRAMONO',
                                    'VITRI HANDAYANI',
                                    'ANDIK TOTOK SISWOYO',
                                    'ARY RODJO PRASETYO',
                                    'HARDI SAPUTRA',
                                    'JESSICA PAUNE',
                                    'MARTINUS CAHYO RAHASTO',
                                    'SITI MARIA ULFA',
                                    'YULMAI RIDO WINANDA',
                                ],
                            ],
                        ],
                        [
                            'label' => 'Riwayat Form Perbaikan',
                            'route' => 'fpps.history',
                            'permissions' => [
                                'usernames' => [
                                    'ADMINSTRATOR',
                                    'ANDI SIMPONI',
                                    'MUGI PRAMONO',
                                    'RANGGA FADILLAH',
                                    'ADHI PRASETIYO',
                                    'ARY RODJO PRASETYO',
                                    'ILHAM CHOLID',
                                    'JESSICA PAUNE',
                                    'JUN JOHAMIN PD',
                                    'KUSTIONO',
                                    'RAGIL ISHA RAHMANTO',
                                    'RICHARDUS CHRISTIAN',
                                    'SITI MARIA ULFA',
                                    'ABDUR RAHMAN AL FAAIZ',
                                ],
                            ],
                        ],
                        [
                            'label' => 'Tabel Preventif',
                            'route' => 'dashboardPreventive',
                            'permissions' => [
                                'usernames' => [
                                    'ADMINSTRATOR',
                                    'ANDI SIMPONI',
                                    'MUGI PRAMONO',
                                    'RANGGA FADILLAH',
                                    'ADHI PRASETIYO',
                                    'ARY RODJO PRASETYO',
                                    'ILHAM CHOLID',
                                    'JESSICA PAUNE',
                                    'JUN JOHAMIN PD',
                                    'KUSTIONO',
                                    'RAGIL ISHA RAHMANTO',
                                    'RICHARDUS CHRISTIAN',
                                    'SITI MARIA ULFA',
                                    'ABDUR RAHMAN AL FAAIZ',
                                ],
                            ],
                        ],
                    ],
                ],
                [
                    'label' => 'Bagian Engineering',
                    'children' => [
                        [
                            'label' => 'Form Tindak Lanjut',
                            'route' => 'submission',
                            'permissions' => [
                                'usernames' => [
                                    'ADMINSTRATOR',
                                    'MUGI PRAMONO',
                                    'ARY RODJO PRASETYO',
                                    'JESSICA PAUNE',
                                ],
                            ],
                        ],
                        [
                            'label' => 'Riwayat Klaim & Komplain',
                            'route' => 'showHistoryCLaimComplain',
                            'permissions' => [
                                'usernames' => [
                                    'ADMINSTRATOR',
                                    'MUGI PRAMONO',
                                    'ARY RODJO PRASETYO',
                                    'JESSICA PAUNE',
                                ],
                            ],
                        ],
                        [
                            'label' => 'Jadwal Kunjungan',
                            'route' => 'scheduleVisit',
                            'permissions' => [
                                'usernames' => [
                                    'ADMINSTRATOR',
                                    'MUGI PRAMONO',
                                    'ARY RODJO PRASETYO',
                                    'JESSICA PAUNE',
                                ],
                            ],
                        ],
                    ],
                ],
                [
                    'label' => 'Maintenance Korektif',
                    'children' => [
                        [
                            'label' => 'Terima Form Perbaikan',
                            'route' => 'dashboardmaintenance',
                            'permissions' => [
                                'usernames' => [
                                    'ADMINSTRATOR',
                                    'ANDI SIMPONI',
                                    'MUGI PRAMONO',
                                    'RANGGA FADILLAH',
                                    'VITRI HANDAYANI',
                                    'ADHI PRASETIYO',
                                    'ANDIK TOTOK SISWOYO',
                                    'ARY RODJO PRASETYO',
                                    'HARDI SAPUTRA',
                                    'ILHAM CHOLID',
                                    'JESSICA PAUNE',
                                    'JUN JOHAMIN PD',
                                    'KUSTIONO',
                                    'MARTINUS CAHYO RAHASTO',
                                    'RAGIL ISHA RAHMANTO',
                                    'RICHARDUS CHRISTIAN',
                                    'SITI MARIA ULFA',
                                    'YULMAI RIDO WINANDA',
                                    'ABDUR RAHMAN AL FAAIZ',
                                ],
                            ],
                        ],
                        [
                            'label' => 'Riwayat Form Perbaikan',
                            'route' => 'fpps.history',
                            'permissions' => [
                                'usernames' => [
                                    'ADMINSTRATOR',
                                    'ANDI SIMPONI',
                                    'MUGI PRAMONO',
                                    'RANGGA FADILLAH',
                                    'ADHI PRASETIYO',
                                    'ARY RODJO PRASETYO',
                                    'ILHAM CHOLID',
                                    'JESSICA PAUNE',
                                    'JUN JOHAMIN PD',
                                    'KUSTIONO',
                                    'RAGIL ISHA RAHMANTO',
                                    'RICHARDUS CHRISTIAN',
                                    'SITI MARIA ULFA',
                                    'ABDUR RAHMAN AL FAAIZ',
                                ],
                            ],
                        ],
                    ],
                ],
                [
                    'label' => 'Maintenance Preventif',
                    'permissions' => [
                        'usernames' => [
                            'ADMINSTRATOR',
                            'ANDI SIMPONI',
                            'MUGI PRAMONO',
                            'RANGGA FADILLAH',
                            'ADHI PRASETIYO',
                            'ARY RODJO PRASETYO',
                            'ILHAM CHOLID',
                            'JESSICA PAUNE',
                            'JUN JOHAMIN PD',
                            'KUSTIONO',
                            'RAGIL ISHA RAHMANTO',
                            'RICHARDUS CHRISTIAN',
                            'SITI MARIA ULFA',
                            'ABDUR RAHMAN AL FAAIZ',
                        ],
                    ],
                    'children' => [
                        [
                            'label' => 'Jadwal Preventif',
                            'route' => 'dashboardPreventiveMaintenance',
                        ],
                    ],
                ],
            ],
        ],
        [
            'label' => 'Procurement',
            'children' => [
                [
                    'label' => 'Overview FPB',
                    'route' => 'overviewfpb',
                ],
                [
                    'label' => 'Form Pengajuan Barang/Jasa',
                    'route' => 'index.PO',
                    'permissions' => [
                        'usernames' => [
                            'ADMINSTRATOR',
                            'DIAMAN DARMAWINATA',
                            'FAIZAL AFDAU',
                            'MEDI KRISNANTO',
                            'MUGI PRAMONO',
                            'NURSALIM',
                            'RANGGA FADILLAH',
                            'ADHI PRASETIYO',
                            'DANIA ISNAWATI',
                            'DWI KUNTORO',
                            'FRISILIA CLAUDIA HUTAMA',
                            'HARRY SUPRIYADI',
                            'HERLIANA',
                            'HERY HERMAWAN',
                            'HUSEIN ABDULLAH',
                            'ILHAM CHOLID',
                            'JESSICA PAUNE',
                            'JUN JOHAMIN PD',
                            'LINA UNIARSIH',
                            'MARTINUS CAHYO RAHASTO',
                            'MUHAMMAD DINAR FARISI',
                            'PUTRI ANINDIA',
                            'RAGIL ISHA RAHMANTO',
                            'RICHARDUS CHRISTIAN',
                            'RISFAN FAISAL',
                            'SENDY PRABOWO',
                            'SITI MARIA ULFA',
                            'WULYO EKO PRASETYO',
                            'YAN WELEM MANGINSELA',
                            'YUNASIS PALGUNADI',
                            'ABDUR RAHMAN AL FAAIZ',
                            'VIVIAN ANGELIKA',
                            'SONY STIAWAN',
                            'FAJAR BAGASKARA',
                            'M. IQBAL',
                            'SARAH EGA BUDI ASTUTI',
                            'YULMAI RIDO WINANDA',
                            'HARDI SAPUTRA',
                        ],
                    ],
                ],
                [
                    'label' => 'Persetujuan Form',
                    'children' => [
                        [
                            'label' => 'User Section',
                            'route' => 'index.PO.user',
                            'permissions' => [
                                'usernames' => [
                                    'ADMINSTRATOR',
                                    'MEDI KRISNANTO',
                                    'JESSICA PAUNE',
                                    'MUHAMMAD DINAR FARISI',
                                    'SITI MARIA ULFA',
                                    'NURSALIM',
                                    'MARTINUS CAHYO RAHASTO',
                                ],
                            ],
                        ],
                        [
                            'label' => 'Ka. Dept',
                            'route' => 'index.PO.Dept',
                            'permissions' => [
                                'usernames' => [
                                    'ADMINSTRATOR',
                                    'ANDIK TOTOK SISWOYO',
                                    'ARY RODJO PRASETYO',
                                    'HARDI SAPUTRA',
                                    'JESSICA PAUNE',
                                    'MARTINUS CAHYO RAHASTO',
                                    'YULMAI RIDO WINANDA',
                                    'ADHI PRASETIYO',
                                    'RICHARDUS CHRISTIAN',
                                    'ILHAM CHOLID',
                                    'ABDUR RAHMAN AL FAAIZ',
                                ],
                            ],
                        ],
                        [
                            'label' => 'Finance Section',
                            'route' => 'index.PO.finance',
                            'permissions' => [
                                'usernames' => [
                                    'ADMINSTRATOR',
                                    'ADHI PRASETIYO',
                                    'JESSICA PAUNE',
                                    'MARTINUS CAHYO RAHASTO',
                                    'RICHARDUS CHRISTIAN',
                                ],
                            ],
                        ],
                        [
                            'label' => 'Procurement Menu 1',
                            'route' => 'index.PO.procurement',
                            'permissions' => [
                                'usernames' => [
                                    'ADMINSTRATOR',
                                    'JESSICA PAUNE',
                                    'VIVIAN ANGELIKA',
                                    'FAJAR BAGASKARA',
                                ],
                            ],
                        ],
                        [
                            'label' => 'Procurement Menu 2',
                            'route' => 'index.PO.procurement2',
                            'permissions' => [
                                'usernames' => [
                                    'ADMINSTRATOR',
                                    'JESSICA PAUNE',
                                    'VIVIAN ANGELIKA',
                                    'FAJAR BAGASKARA',
                                ],
                            ],
                        ],
                    ],
                ],
                [
                    'label' => 'Penawaran Subcont Project Sales',
                    'children' => [
                        [
                            'label' => 'Form Penawaran Subcont',
                            'route' => 'indexSales',
                            'permissions' => [
                                'usernames' => [
                                    'ADMINSTRATOR',
                                    'JESSICA PAUNE',
                                    'RAGIL ISHA RAHMANTO',
                                    'SARAH EGA BUDI ASTUTI',
                                ],
                            ],
                        ],
                        [
                            'label' => 'Persetujuan Subcont',
                            'route' => 'indexProc',
                            'permissions' => [
                                'usernames' => [
                                    'ADMINSTRATOR',
                                    'JESSICA PAUNE',
                                    'VIVIAN ANGELIKA',
                                    'FAJAR BAGASKARA',
                                ],
                            ],
                        ],
                    ],
                ],
                [
                    'label' => 'Claim Submission',
                    'children' => [
                        [
                            'label' => 'Form Claim Submission',
                            'route' => 'claim.indexUser',
                        ],
                        [
                            'label' => 'Persetujuan Claim Submission',
                            'route' => 'claim.indexProc',
                            'permissions' => [
                                'usernames' => [
                                    'ADMINSTRATOR',
                                    'JESSICA PAUNE',
                                    'VIVIAN ANGELIKA',
                                    'FAJAR BAGASKARA',
                                ],
                            ],
                        ],
                    ],
                ],
                [
                    'label' => 'Inquiry Order Local',
                    'children' => [
                        [
                            'label' => 'Form Inquiry Local',
                            'route' => 'createinquiry',
                            'permissions' => [
                                'usernames' => [
                                    'ADMINSTRATOR',
                                    'ANDIK TOTOK SISWOYO',
                                    'DANIA ISNAWATI',
                                    'DWI KUNTORO',
                                    'ILHAM CHOLID',
                                    'JESSICA PAUNE',
                                    'JUN JOHAMIN PD',
                                    'LINA UNIARSIH',
                                    'MARTINUS CAHYO RAHASTO',
                                    'RISFAN FAISAL',
                                    'SENDY PRABOWO',
                                    'WULYO EKO PRASETYO',
                                    'YAN WELEM MANGINSELA',
                                    'YULMAI RIDO WINANDA',
                                    'YUNASIS PALGUNADI',
                                    'SARAH EGA BUDI ASTUTI',
                                    'DIMAS ADITYA PRIANDANA',
                                    'HEXAPA DARMADI',
                                    'HERY HERMAWAN',
                                    'SONY STIAWAN',
                                    'FISKA CHRISMAS YUDHA',
                                ],
                            ],
                        ],
                        [
                            'label' => 'Persetujuan Ka. Sie',
                            'route' => 'showApprovalKaSie',
                            'permissions' => [
                                'usernames' => [
                                    'ADMINSTRATOR',
                                    'MUGI PRAMONO',
                                    'ANDIK TOTOK SISWOYO',
                                    'ILHAM CHOLID',
                                    'JESSICA PAUNE',
                                    'JUN JOHAMIN PD',
                                ],
                            ],
                        ],
                        [
                            'label' => 'Persetujuan Ka. Dept',
                            'route' => 'showApprovalKaDept',
                            'permissions' => [
                                'usernames' => [
                                    'ADMINSTRATOR',
                                    'ANDIK TOTOK SISWOYO',
                                    'JESSICA PAUNE',
                                    'YULMAI RIDO WINANDA',
                                ],
                            ],
                        ],
                        [
                            'label' => 'Persetujuan Inventory',
                            'route' => 'showApprovalInventory',
                            'permissions' => [
                                'usernames' => [
                                    'ADMINSTRATOR',
                                    'M. IQBAL',
                                ],
                            ],
                        ],
                        [
                            'label' => 'Overview Purchase',
                            'route' => 'overviewPurchase',
                            'permissions' => [
                                'usernames' => [
                                    'ADMINSTRATOR',
                                    'JESSICA PAUNE',
                                    'VIVIAN ANGELIKA',
                                    'M. IQBAL',
                                ],
                            ],
                        ],
                        [
                            'label' => 'Overview Purchase 2',
                            'route' => 'overviewPurchase2',
                            'permissions' => [
                                'usernames' => [
                                    'ADMINSTRATOR',
                                    'JESSICA PAUNE',
                                    'VIVIAN ANGELIKA',
                                    'M. IQBAL',
                                ],
                            ],
                        ],
                        [
                            'label' => 'Overview Inquiry Order Local',
                            'route' => 'overviewInquiry',
                        ],
                    ],
                ],
                [
                    'label' => 'Inquiry Order Import',
                    'children' => [
                        [
                            'label' => 'Form Inquiry Import',
                            'route' => 'createinquiryImport',
                        ],
                        [
                            'label' => 'Persetujuan Inventory',
                            'route' => 'showApprovalInventoryImport',
                        ],
                        [
                            'label' => 'Overview Purchasing Import',
                            'route' => 'overviewPurchaseImport',
                        ],
                        [
                            'label' => 'Overview Inquiry Import',
                            'route' => 'overviewInquiryImport',
                        ],
                    ],
                ],
                [
                    'label' => 'Import Administration',
                    'children' => [
                        [
                            'label' => 'Form Administration Purchasing',
                            'route' => 'createadministration',
                        ],
                        [
                            'label' => 'Form Administration Admin',
                            'route' => 'createadministration',
                        ],
                    ],
                ],
                [
                    'label' => 'Supplier Form',
                    'children' => [
                        [
                            'label' => 'Index Supplier',
                            'route' => 'supplierform.index',
                        ],
                    ],
                ],
            ],
        ],
        [
            'label' => 'Human Resource',
            'children' => [
                [
                    'label' => 'Pengajuan Form Knowledge Management',
                    'children' => [
                        [
                            'label' => 'Form Knowledge Management',
                            'route' => 'pengajuanKM',
                            'permissions' => [
                                'usernames' => [
                                    'ADMINSTRATOR',
                                    'MUGI PRAMONO',
                                    'YULMAI RIDO WINANDA',
                                    'SITI MARIA ULFA',
                                    'JESSICA PAUNE',
                                    'ADHI PRASETIYO',
                                    'ANDIK TOTOK SISWOYO',
                                    'RICHARDUS CHRISTIAN',
                                ],
                            ],
                        ],
                        [
                            'label' => 'Persetujuan Knowledge Management',
                            'route' => 'persetujuanKM',
                            'permissions' => [
                                'usernames' => [
                                    'ADMINSTRATOR',
                                    'MUGI PRAMONO',
                                    'YULMAI RIDO WINANDA',
                                    'SITI MARIA ULFA',
                                    'JESSICA PAUNE',
                                    'ADHI PRASETIYO',
                                    'ANDIK TOTOK SISWOYO',
                                    'RICHARDUS CHRISTIAN',
                                ],
                            ],
                        ],
                    ],
                ],
                [
                    'label' => 'Base Competency',
                    'children' => [
                        [
                            'label' => 'Form Job Position',
                            'route' => 'jobShow',
                            'permissions' => [
                                'usernames' => [
                                    'ADMINSTRATOR',
                                    'JESSICA PAUNE',
                                    'SITI MARIA ULFA',
                                ],
                            ],
                        ],
                        [
                            'label' => 'Form Pengajuan Competency',
                            'route' => 'tcShow',
                            'permissions' => [
                                'usernames' => [
                                    'ADMINSTRATOR',
                                    'YULMAI RIDO WINANDA',
                                    'ANDIK TOTOK SISWOYO',
                                    'ARY RODJO PRASETYO',
                                    'HARDI SAPUTRA',
                                    'JESSICA PAUNE',
                                    'MARTINUS CAHYO RAHASTO',
                                    'SITI MARIA ULFA',
                                    'RICHARDUS CHRISTIAN',
                                    'MUGI PRAMONO',
                                    'ABDUR RAHMAN AL FAAIZ',
                                    'RAGIL ISHA RAHMANTO',
                                ],
                            ],
                        ],
                        [
                            'label' => 'Penilaian Technical Competency Ka. Sie',
                            'route' => 'penilaian.index',
                            'permissions' => [
                                'role_prefixes' => ['SC'],
                                'usernames' => [
                                    'ADMINSTRATOR',
                                    'JESSICA PAUNE',
                                    'SITI MARIA ULFA',
                                ],
                            ],
                        ],
                        [
                            'label' => 'Penilaian Technical Competency Ka. Dept',
                            'route' => 'penilaian.index2',
                            'permissions' => [
                                'role_prefixes' => ['DH'],
                                'usernames' => [
                                    'ADMINSTRATOR',
                                    'JESSICA PAUNE',
                                    'SITI MARIA ULFA',
                                ],
                            ],
                        ],
                        [
                            'label' => 'Penilaian Technical Competency HR',
                            'route' => 'penilaian.index3',
                            'permissions' => [
                                'usernames' => [
                                    'ADMINSTRATOR',
                                    'JESSICA PAUNE',
                                    'SITI MARIA ULFA',
                                ],
                            ],
                        ],
                        [
                            'label' => 'Summary Competency',
                            'route' => 'job.positions.index',
                            'permissions' => [
                                'usernames' => [
                                    'ADMINSTRATOR',
                                    'AFILIANDI',
                                    'AGUNG PANGESTU YUSUF',
                                    'AGUS PRIYANTO',
                                    'AGUS ROSIDIN',
                                    'ANDI SANTOSO',
                                    'ANDI SIMPONI',
                                    'ARRY SOEBHEKTI',
                                    'AWING',
                                    'DASUKI',
                                    'DEDY SETIAWAN',
                                    'DIAMAN DARMAWINATA',
                                    'ELI HANDOYO',
                                    'FAIZAL AFDAU',
                                    'FATUL MUKMIN',
                                    'HAERUL IKHSAN',
                                    'HENDRIO',
                                    'JAKA RARA SUKMA',
                                    'JAKARIA',
                                    'KARYA WIJAYA',
                                    'LUKMAN AHMAD',
                                    'MAMIK ABIDIN',
                                    'MEDI KRISNANTO',
                                    'MIFTAKHUROHMAN',
                                    'MUGI PRAMONO',
                                    'NUR SUPRIYANTO',
                                    'NURSAID',
                                    'NURSALIM',
                                    'R.WAWAN HIMAWAN',
                                    'RAHMAT NUGROHO',
                                    'RANGGA FADILLAH',
                                    'RIZKY ANDREA RAHMAWAN',
                                    'RUKMAN',
                                    'RUSITO',
                                    'SABAR WASIRAN',
                                    'SEPTIADI PRATOMO',
                                    'SUDIYATNO',
                                    'UMAR HADI',
                                    'VITRI HANDAYANI',
                                    'YANUARDIN SALEH SIREGAR',
                                    'YUSUF SYAFAAT',
                                    'ADHI PRASETIYO',
                                    'AHMAD RIDWAN',
                                    'ANDIK TOTOK SISWOYO',
                                    'ARY RODJO PRASETYO',
                                    'AVI SHENNA',
                                    'BANGUN SUTOPO',
                                    'CECEP ISKANDAR',
                                    'DANIA ISNAWATI',
                                    'DINA NIMAS AYU NAWAWULAN PRIHANTINI',
                                    'DWI KUNTORO',
                                    'FIKRI SYAHBANA',
                                    'FRISILIA CLAUDIA HUTAMA',
                                    'GUNAWAN',
                                    'HARDI SAPUTRA',
                                    'HARRY SUPRIYADI',
                                    'HERLIANA',
                                    'HERY HERMAWAN',
                                    'HUSEIN ABDULLAH',
                                    'ILHAM CHOLID',
                                    'ILHAM SETIA DARMA',
                                    'IMAM PRASETYO',
                                    'IMAM SOPYAN',
                                    'JEFRY WASTON E',
                                    'JESSICA PAUNE',
                                    'JONI SETIAWAN',
                                    'JUN JOHAMIN PD',
                                    'KUSTIONO',
                                    'LINA UNIARSIH',
                                    'M. RIDWAN GUNAWAN',
                                    'MARTINUS CAHYO RAHASTO',
                                    'MOCHAMMAD ANDRIANSYAH',
                                    'MOHAMMAD FATKHURROHMAN',
                                    'MUHAMMAD DINAR FARISI',
                                    'MUHAMMAD MAHBUB',
                                    'NUR DWITA SURA WIJAYA',
                                    'PUTRI ANINDIA',
                                    'RAGIL ISHA RAHMANTO',
                                    'RIADUS SOLIHIN',
                                    'RICHARDUS CHRISTIAN',
                                    'RISFAN FAISAL',
                                    'RUSLAN M.ALI',
                                    'SENDY PRABOWO',
                                    'SETIYAWAN',
                                    'SITI MARIA ULFA',
                                ],
                            ],
                        ],
                    ],
                ],
                [
                    'label' => 'Training Development',
                    'children' => [
                        [
                            'label' => 'Form Pengajuan Training',
                            'route' => 'indexPD',
                            'permissions' => [
                                'role_prefixes' => ['DH'],
                                'usernames' => [
                                    'ADMINSTRATOR',
                                    'JESSICA PAUNE',
                                    'SITI MARIA ULFA',
                                ],
                            ],
                        ],
                        [
                            'label' => 'Persetujuan Development',
                            'route' => 'indexPD2',
                            'permissions' => [
                                'usernames' => [
                                    'ADMINSTRATOR',
                                    'JESSICA PAUNE',
                                    'SITI MARIA ULFA',
                                ],
                            ],
                        ],
                        [
                            'label' => 'History Development',
                            'route' => 'historiDept',
                            'permissions' => [
                                'role_prefixes' => ['SC', 'DH'],
                                'usernames' => [
                                    'ADMINSTRATOR',
                                    'JESSICA PAUNE',
                                    'SITI MARIA ULFA',
                                ],
                            ],
                        ],
                    ],
                ],
            ],
        ],
        [
            'label' => 'CRP System',
            'children' => [
                [
                    'label' => 'Form CRP',
                    'route' => 'crp',
                ],
            ],
        ],
        [
            'label' => 'Sumbang Saran',
            'children' => [
                [
                    'label' => 'Upload JSON to CSV',
                    'route' => 'upload.json',
                    'permissions' => [
                        'usernames' => [
                            'ADMINSTRATOR',
                            'AFILIANDI',
                            'AGUNG PANGESTU YUSUF',
                            'AGUS PRIYANTO',
                            'AGUS ROSIDIN',
                            'ANDI SANTOSO',
                            'ANDI SIMPONI',
                            'ARRY SOEBHEKTI',
                            'AWING',
                            'DASUKI',
                            'DEDY SETIAWAN',
                            'DIAMAN DARMAWINATA',
                            'ELI HANDOYO',
                            'FAIZAL AFDAU',
                            'FATUL MUKMIN',
                            'HAERUL IKHSAN',
                            'HENDRIO',
                            'JAKA RARA SUKMA',
                            'JAKARIA',
                            'KARYA WIJAYA',
                            'LUKMAN AHMAD',
                            'MAMIK ABIDIN',
                            'MEDI KRISNANTO',
                            'MIFTAKHUROHMAN',
                            'MUGI PRAMONO',
                            'NUR SUPRIYANTO',
                            'NURSAID',
                            'NURSALIM',
                            'R.WAWAN HIMAWAN',
                            'RAHMAT NUGROHO',
                            'RANGGA FADILLAH',
                            'RIZKY ANDREA RAHMAWAN',
                            'RUKMAN',
                            'RUSITO',
                            'SABAR WASIRAN',
                            'SEPTIADI PRATOMO',
                            'SUDIYATNO',
                            'UMAR HADI',
                            'VITRI HANDAYANI',
                            'YANUARDIN SALEH SIREGAR',
                            'YUSUF SYAFAAT',
                            'ADHI PRASETIYO',
                            'AHMAD RIDWAN',
                            'ANDIK TOTOK SISWOYO',
                            'ARY RODJO PRASETYO',
                            'AVI SHENNA',
                            'BANGUN SUTOPO',
                            'CECEP ISKANDAR',
                            'DANIA ISNAWATI',
                            'DINA NIMAS AYU NAWAWULAN PRIHANTINI',
                            'DWI KUNTORO',
                            'FIKRI SYAHBANA',
                            'FRISILIA CLAUDIA HUTAMA',
                            'GUNAWAN',
                            'HARDI SAPUTRA',
                            'HARRY SUPRIYADI',
                            'HERLIANA',
                            'HERY HERMAWAN',
                            'HUSEIN ABDULLAH',
                            'ILHAM CHOLID',
                            'ILHAM SETIA DARMA',
                            'IMAM PRASETYO',
                            'IMAM SOPYAN',
                            'JEFRY WASTON E',
                            'JESSICA PAUNE',
                            'JONI SETIAWAN',
                            'JUN JOHAMIN PD',
                            'KUSTIONO',
                            'LINA UNIARSIH',
                            'M. RIDWAN GUNAWAN',
                            'MARTINUS CAHYO RAHASTO',
                            'MOCHAMMAD ANDRIANSYAH',
                            'MOHAMMAD FATKHURROHMAN',
                            'MUHAMMAD DINAR FARISI',
                            'MUHAMMAD MAHBUB',
                            'NUR DWITA SURA WIJAYA',
                            'PUTRI ANINDIA',
                            'RAGIL ISHA RAHMANTO',
                            'RIADUS SOLIHIN',
                            'RICHARDUS CHRISTIAN',
                            'RISFAN FAISAL',
                            'RUSLAN M.ALI',
                            'SENDY PRABOWO',
                            'SETIYAWAN',
                            'SITI MARIA ULFA',
                            'SUKIMIN',
                            'WULYO EKO PRASETYO',
                            'YAN WELEM MANGINSELA',
                            'YUDHI PRASETYO RAHMAWANTO',
                            'YULMAI RIDO WINANDA',
                            'YUNASIS PALGUNADI',
                            'ZAENAL ARIFIN',
                            'ABDUR RAHMAN AL FAAIZ',
                            'YAN WALEM MANGINSELA',
                            'VIVIAN ANGELIKA',
                            'SONY STIAWAN',
                            'FAJAR BAGASKARA',
                        ],
                    ],
                ],
                [
                    'label' => 'Form Sumbang Saran',
                    'route' => 'showSS',
                    'permissions' => [
                        'usernames' => [
                            'ADMINSTRATOR',
                            'AFILIANDI',
                            'AGUNG PANGESTU YUSUF',
                            'AGUS PRIYANTO',
                            'AGUS ROSIDIN',
                            'ANDI SANTOSO',
                            'ANDI SIMPONI',
                            'ARRY SOEBHEKTI',
                            'AWING',
                            'DASUKI',
                            'DEDY SETIAWAN',
                            'DIAMAN DARMAWINATA',
                            'ELI HANDOYO',
                            'FAIZAL AFDAU',
                            'FATUL MUKMIN',
                            'HAERUL IKHSAN',
                            'HENDRIO',
                            'JAKA RARA SUKMA',
                            'JAKARIA',
                            'KARYA WIJAYA',
                            'LUKMAN AHMAD',
                            'MAMIK ABIDIN',
                            'MEDI KRISNANTO',
                            'MIFTAKHUROHMAN',
                            'MUGI PRAMONO',
                            'NUR SUPRIYANTO',
                            'NURSAID',
                            'NURSALIM',
                            'R.WAWAN HIMAWAN',
                            'RAHMAT NUGROHO',
                            'RANGGA FADILLAH',
                            'RIZKY ANDREA RAHMAWAN',
                            'RUKMAN',
                            'RUSITO',
                            'SABAR WASIRAN',
                            'SEPTIADI PRATOMO',
                            'SUDIYATNO',
                            'UMAR HADI',
                            'VITRI HANDAYANI',
                            'YANUARDIN SALEH SIREGAR',
                            'YUSUF SYAFAAT',
                            'ADHI PRASETIYO',
                            'AHMAD RIDWAN',
                            'ANDIK TOTOK SISWOYO',
                            'ARY RODJO PRASETYO',
                            'AVI SHENNA',
                            'BANGUN SUTOPO',
                            'CECEP ISKANDAR',
                            'DANIA ISNAWATI',
                            'DINA NIMAS AYU NAWAWULAN PRIHANTINI',
                            'DWI KUNTORO',
                            'FIKRI SYAHBANA',
                            'FRISILIA CLAUDIA HUTAMA',
                            'GUNAWAN',
                            'HARDI SAPUTRA',
                            'HARRY SUPRIYADI',
                            'HERLIANA',
                            'HERY HERMAWAN',
                            'HUSEIN ABDULLAH',
                            'ILHAM CHOLID',
                            'ILHAM SETIA DARMA',
                            'IMAM PRASETYO',
                            'IMAM SOPYAN',
                            'JEFRY WASTON E',
                            'JESSICA PAUNE',
                            'JONI SETIAWAN',
                            'JUN JOHAMIN PD',
                            'KUSTIONO',
                            'LINA UNIARSIH',
                            'M. RIDWAN GUNAWAN',
                            'MARTINUS CAHYO RAHASTO',
                            'MOCHAMMAD ANDRIANSYAH',
                            'MOHAMMAD FATKHURROHMAN',
                            'MUHAMMAD DINAR FARISI',
                            'MUHAMMAD MAHBUB',
                            'NUR DWITA SURA WIJAYA',
                            'PUTRI ANINDIA',
                            'RAGIL ISHA RAHMANTO',
                            'RIADUS SOLIHIN',
                            'RICHARDUS CHRISTIAN',
                            'RISFAN FAISAL',
                            'RUSLAN M.ALI',
                            'SENDY PRABOWO',
                            'SETIYAWAN',
                            'SITI MARIA ULFA',
                            'SUKIMIN',
                            'WULYO EKO PRASETYO',
                            'YAN WELEM MANGINSELA',
                            'YUDHI PRASETYO RAHMAWANTO',
                            'YULMAI RIDO WINANDA',
                            'YUNASIS PALGUNADI',
                            'ZAENAL ARIFIN',
                            'ABDUR RAHMAN AL FAAIZ',
                            'YAN WALEM MANGINSELA',
                            'VIVIAN ANGELIKA',
                            'SONY STIAWAN',
                            'FAJAR BAGASKARA',
                        ],
                    ],
                ],
                [
                    'label' => 'Overview Sumbang Saran',
                    'route' => 'forumSS',
                    'permissions' => [
                        'usernames' => [
                            'ADMINSTRATOR',
                            'AFILIANDI',
                            'AGUNG PANGESTU YUSUF',
                            'AGUS PRIYANTO',
                            'AGUS ROSIDIN',
                            'ANDI SANTOSO',
                            'ANDI SIMPONI',
                            'ARRY SOEBHEKTI',
                            'AWING',
                            'DASUKI',
                            'DEDY SETIAWAN',
                            'DIAMAN DARMAWINATA',
                            'ELI HANDOYO',
                            'FAIZAL AFDAU',
                            'FATUL MUKMIN',
                            'HAERUL IKHSAN',
                            'HENDRIO',
                            'JAKA RARA SUKMA',
                            'JAKARIA',
                            'KARYA WIJAYA',
                            'LUKMAN AHMAD',
                            'MAMIK ABIDIN',
                            'MEDI KRISNANTO',
                            'MIFTAKHUROHMAN',
                            'MUGI PRAMONO',
                            'NUR SUPRIYANTO',
                            'NURSAID',
                            'NURSALIM',
                            'R.WAWAN HIMAWAN',
                            'RAHMAT NUGROHO',
                            'RANGGA FADILLAH',
                            'RIZKY ANDREA RAHMAWAN',
                            'RUKMAN',
                            'RUSITO',
                            'SABAR WASIRAN',
                            'SEPTIADI PRATOMO',
                            'SUDIYATNO',
                            'UMAR HADI',
                            'VITRI HANDAYANI',
                            'YANUARDIN SALEH SIREGAR',
                            'YUSUF SYAFAAT',
                            'ADHI PRASETIYO',
                            'AHMAD RIDWAN',
                            'ANDIK TOTOK SISWOYO',
                            'ARY RODJO PRASETYO',
                            'AVI SHENNA',
                            'BANGUN SUTOPO',
                            'CECEP ISKANDAR',
                            'DANIA ISNAWATI',
                            'DINA NIMAS AYU NAWAWULAN PRIHANTINI',
                            'DWI KUNTORO',
                            'FIKRI SYAHBANA',
                            'FRISILIA CLAUDIA HUTAMA',
                            'GUNAWAN',
                            'HARDI SAPUTRA',
                            'HARRY SUPRIYADI',
                            'HERLIANA',
                            'HERY HERMAWAN',
                            'HUSEIN ABDULLAH',
                            'ILHAM CHOLID',
                            'ILHAM SETIA DARMA',
                            'IMAM PRASETYO',
                            'IMAM SOPYAN',
                            'JEFRY WASTON E',
                            'JESSICA PAUNE',
                            'JONI SETIAWAN',
                            'JUN JOHAMIN PD',
                            'KUSTIONO',
                            'LINA UNIARSIH',
                            'M. RIDWAN GUNAWAN',
                            'MARTINUS CAHYO RAHASTO',
                            'MOCHAMMAD ANDRIANSYAH',
                            'MOHAMMAD FATKHURROHMAN',
                            'MUHAMMAD DINAR FARISI',
                            'MUHAMMAD MAHBUB',
                            'NUR DWITA SURA WIJAYA',
                            'PUTRI ANINDIA',
                            'RAGIL ISHA RAHMANTO',
                            'RIADUS SOLIHIN',
                            'RICHARDUS CHRISTIAN',
                            'RISFAN FAISAL',
                            'RUSLAN M.ALI',
                            'SENDY PRABOWO',
                            'SETIYAWAN',
                            'SITI MARIA ULFA',
                            'SUKIMIN',
                            'WULYO EKO PRASETYO',
                            'YAN WELEM MANGINSELA',
                            'YUDHI PRASETYO RAHMAWANTO',
                            'YULMAI RIDO WINANDA',
                            'YUNASIS PALGUNADI',
                            'ZAENAL ARIFIN',
                            'ABDUR RAHMAN AL FAAIZ',
                            'YAN WALEM MANGINSELA',
                            'VIVIAN ANGELIKA',
                            'SONY STIAWAN',
                            'FAJAR BAGASKARA',
                        ],
                    ],
                ],
                [
                    'label' => 'Persetujuan Atasan',
                    'children' => [
                        [
                            'label' => 'Ka. Sie',
                            'route' => 'showKonfirmasiForeman',
                            'permissions' => [
                                'usernames' => [
                                    'ADMINSTRATOR',
                                    'MUGI PRAMONO',
                                    'RANGGA FADILLAH',
                                    'VITRI HANDAYANI',
                                    'ADHI PRASETIYO',
                                    'ANDIK TOTOK SISWOYO',
                                    'ARY RODJO PRASETYO',
                                    'HARDI SAPUTRA',
                                    'ILHAM CHOLID',
                                    'JESSICA PAUNE',
                                    'JUN JOHAMIN PD',
                                    'MARTINUS CAHYO RAHASTO',
                                    'RAGIL ISHA RAHMANTO',
                                    'RICHARDUS CHRISTIAN',
                                    'SITI MARIA ULFA',
                                    'YUDHI PRASETYO RAHMAWANTO',
                                    'ABDUR RAHMAN AL FAAIZ',
                                ],
                            ],
                        ],
                        [
                            'label' => 'Ka. Dept',
                            'route' => 'showKonfirmasiDeptHead',
                            'permissions' => [
                                'usernames' => [
                                    'ADMINSTRATOR',
                                    'MUGI PRAMONO',
                                    'RANGGA FADILLAH',
                                    'ADHI PRASETIYO',
                                    'ARY RODJO PRASETYO',
                                    'ILHAM CHOLID',
                                    'JESSICA PAUNE',
                                    'JUN JOHAMIN PD',
                                    'RAGIL ISHA RAHMANTO',
                                    'RICHARDUS CHRISTIAN',
                                    'SITI MARIA ULFA',
                                    'ABDUR RAHMAN AL FAAIZ',
                                ],
                            ],
                        ],
                    ],
                ],
                [
                    'label' => 'Penilaian',
                    'children' => [
                        [
                            'label' => 'Penilaian Komite',
                            'route' => 'showKonfirmasiKomite',
                            'permissions' => [
                                'usernames' => [
                                    'ADMINSTRATOR',
                                    'ARY RODJO PRASETYO',
                                    'JESSICA PAUNE',
                                    'SITI MARIA ULFA',
                                ],
                            ],
                        ],
                        [
                            'label' => 'Penilaian HRGA',
                            'route' => 'showKonfirmasiHRGA',
                            'permissions' => [
                                'usernames' => [
                                    'ADMINSTRATOR',
                                    'ARY RODJO PRASETYO',
                                    'JESSICA PAUNE',
                                    'SITI MARIA ULFA',
                                ],
                            ],
                        ],
                    ],
                ],
            ],
        ],
        [
            'label' => 'Logout',
            'route' => 'logout',
            'buttonLabel' => 'Keluar Aplikasi',
        ],
    ],
];
