@extends('warehouse.layout')

@push('styles')
    @vite('resources/css/warehouse/management.css')
@endpush

@section('warehouse-content')
    <div class="warehouse-management-page" aria-labelledby="warehouse-receipt-title">
        <x-warehouse.page-header title="Detail Transaksi" subtitle="Receipt audit yang tidak dapat diubah atau dihapus."><a class="btn btn-outline-secondary" href="{{ route('warehouse.transactions.index') }}">Riwayat</a><a class="btn btn-outline-secondary" href="{{ route('warehouse.dashboard') }}">Dashboard</a></x-warehouse.page-header>
        @if(session('status'))<div class="alert alert-success" role="status">{{ session('status') }}</div>@endif
        <x-warehouse.panel title="Metadata Receipt" class="warehouse-detail-grid warehouse-detail-full"><dl class="warehouse-definition-list">
            <dt>Nomor transaksi</dt><dd class="font-monospace">{{ $transaction->transaction_number }}</dd><dt>Operation key</dt><dd class="font-monospace">{{ $transaction->operation_key ?: '—' }}</dd><dt>Tipe</dt><dd><x-warehouse.status-badge :status="$transaction->transaction_type?->value" context="transaction" /></dd><dt>Kondisi</dt><dd>{{ $transaction->item_condition?->label() ?? 'Baru' }}</dd><dt>Barang</dt><dd>{{ $transaction->consumable?->item_name }} ({{ $transaction->consumable?->item_code }})</dd><dt>Tipe mesin</dt><dd>{{ $transaction->consumable?->machine_type ?: '—' }}</dd><dt>Jumlah</dt><dd>{{ \App\Services\Warehouse\WarehouseQuantity::display($transaction->quantity) }} {{ $transaction->consumable?->unit }}</dd><dt>Lokasi asal</dt><dd>{{ $transaction->from_location ?: '—' }}</dd><dt>Lokasi tujuan</dt><dd>{{ $transaction->to_location ?: '—' }}</dd><dt>Stok total sebelum → sesudah</dt><dd><strong>{{ \App\Services\Warehouse\WarehouseQuantity::display($transaction->stock_before) }} → {{ \App\Services\Warehouse\WarehouseQuantity::display($transaction->stock_after) }}</strong></dd><dt>Karyawan verifikator</dt><dd>{{ $transaction->verified_user_name }} · NPK {{ $transaction->verified_user_npk ?: '—' }} · {{ $transaction->verified_user_section ?: '—' }}</dd><dt>Waktu transaksi</dt><dd>{{ optional($transaction->transaction_at)->format('Y-m-d H:i:s') }}</dd><dt>Dibuat oleh</dt><dd>{{ $transaction->creator?->name ?: '—' }}</dd><dt>Catatan</dt><dd>{{ $transaction->notes ?: '—' }}</dd>@if($transaction->reversalOf)<dt>Membatalkan transaksi</dt><dd><a href="{{ route('warehouse.transactions.show', $transaction->reversalOf) }}">{{ $transaction->reversalOf->transaction_number }}</a></dd>@endif @if($transaction->reversal)<dt>Dibatalkan oleh</dt><dd><a href="{{ route('warehouse.transactions.show', $transaction->reversal) }}">{{ $transaction->reversal->transaction_number }}</a></dd>@endif
        </dl></x-warehouse.panel>
        @if($transaction->transaction_type?->value === 'TRANSFER')<div class="alert alert-info mt-3" role="note">Transfer tidak direversal. Jika lokasi atau jumlah salah, buat transfer balik sebagai koreksi audit.</div>@endif
        <div class="warehouse-action-bar mt-3"><a class="btn btn-primary" href="{{ route('warehouse.transactions.create') }}">Transaksi Baru</a>@if($canReverse)<a class="btn btn-outline-danger" href="{{ route('warehouse.transactions.reverse-form', $transaction) }}">Buat Pembatalan</a>@endif<a class="btn btn-outline-secondary" href="{{ route('warehouse.dashboard') }}">Dashboard</a></div>
    </div>
@endsection
