@extends('warehouse.layout')

@push('styles')
    @vite('resources/css/warehouse/location-shipments.css')
@endpush

@section('warehouse-content')
    <div class="warehouse-shipment-page" aria-labelledby="warehouse-shipment-show-title">
        <x-warehouse.page-header title="Detail Pengiriman Antar Lokasi" subtitle="Audit pengirim, serah terima, Validator, dan transaksi lokasi."><a class="btn btn-outline-secondary" href="{{ route('warehouse.location-shipments.index') }}">Kembali</a></x-warehouse.page-header>
        @if (session('status'))<div class="alert alert-success" role="status">{{ session('status') }}</div>@endif
        <section class="warehouse-panel warehouse-shipment-detail-card"><div class="warehouse-panel-header"><div><span class="warehouse-eyebrow">{{ $shipment->shipment_number }}</span><h2>{{ $shipment->status?->value === 'DISCREPANCY' ? 'Tidak Sesuai — Perlu Penanganan' : 'Status '.$shipment->status?->value }}</h2></div><x-warehouse.status-badge :status="$shipment->status?->value" context="shipment" /></div><div class="warehouse-panel-body"><dl class="warehouse-shipment-detail-grid"><div><dt>Barang</dt><dd>{{ $shipment->consumable?->item_name }} ({{ $shipment->consumable?->item_code }})</dd></div><div><dt>Kondisi dikirim</dt><dd>{{ $shipment->item_condition?->label() }}</dd></div><div><dt>Qty dikirim</dt><dd>{{ \App\Services\Warehouse\WarehouseQuantity::display($shipment->quantity_sent) }} {{ $shipment->consumable?->unit }}</dd></div><div><dt>Asal</dt><dd>{{ $shipment->from_location }}</dd></div><div><dt>Tujuan</dt><dd>{{ $shipment->to_location }}</dd></div><div><dt>Pengirim</dt><dd>{{ $shipment->sender_name_snapshot }} @if($shipment->sender_npk_snapshot)<small class="d-block warehouse-muted">NPK {{ $shipment->sender_npk_snapshot }}</small>@endif</dd></div><div><dt>Dikirim</dt><dd>{{ optional($shipment->sent_at)->locale('id')->translatedFormat('d M Y H:i') }}</dd></div><div><dt>Catatan Pengirim</dt><dd>{{ $shipment->sender_notes ?: '—' }}</dd></div><div><dt>Qty diterima</dt><dd>{{ $shipment->received_quantity === null ? '—' : \App\Services\Warehouse\WarehouseQuantity::display($shipment->received_quantity) }}</dd></div><div><dt>Kondisi diterima</dt><dd>{{ $shipment->received_condition?->label() ?: '—' }}</dd></div><div><dt>Validator</dt><dd>{{ $shipment->validator_name_snapshot ?: '—' }} @if($shipment->validator_npk_snapshot)<small class="d-block warehouse-muted">NPK {{ $shipment->validator_npk_snapshot }}</small>@endif</dd></div><div><dt>Catatan Validasi</dt><dd>{{ $shipment->validation_notes ?: '—' }}</dd></div><div><dt>Transaksi stok</dt><dd>@if($shipment->stockTransaction)<a href="{{ route('warehouse.transactions.show', $shipment->stockTransaction) }}">{{ $shipment->stockTransaction->transaction_number }}</a>@else—@endif</dd></div></dl></div>
            @if($shipment->canValidate())<div class="card-footer d-flex flex-wrap gap-2">@can('warehouse.location-shipment.validate')<a class="btn btn-primary" href="{{ route('warehouse.location-shipments.validate-form', $shipment) }}">Serah Terima & Validasi</a>@endcan @can('warehouse.location-shipment.cancel')<details class="warehouse-inline-cancel"><summary class="btn btn-outline-danger">Batalkan</summary><form method="POST" action="{{ route('warehouse.location-shipments.cancel', $shipment) }}" class="warehouse-inline-cancel-form">@csrf<input type="hidden" name="idempotency_key" value="{{ (string) str()->uuid() }}"><label class="form-label warehouse-required" for="cancel-reason">Alasan pembatalan</label><textarea class="form-control" id="cancel-reason" name="reason" rows="2" required></textarea><button class="btn btn-danger mt-2" type="submit">Konfirmasi Pembatalan</button></form></details>@endcan</div>@elseif($shipment->canCancel())<div class="card-footer">@can('warehouse.location-shipment.cancel')<details class="warehouse-inline-cancel"><summary class="btn btn-outline-danger">Batalkan Discrepancy</summary><form method="POST" action="{{ route('warehouse.location-shipments.cancel', $shipment) }}" class="warehouse-inline-cancel-form">@csrf<input type="hidden" name="idempotency_key" value="{{ (string) str()->uuid() }}"><label class="form-label warehouse-required" for="cancel-reason-discrepancy">Alasan pembatalan</label><textarea class="form-control" id="cancel-reason-discrepancy" name="reason" rows="2" required></textarea><button class="btn btn-danger mt-2" type="submit">Konfirmasi Pembatalan</button></form></details>@endcan</div>@endif
        </section>
    </div>
@endsection
