@extends('warehouse.layout')

@push('styles')
    @vite('resources/css/warehouse/management.css')
@endpush

@section('warehouse-content')
    <div class="warehouse-management-page" aria-labelledby="warehouse-consumable-detail-title">
        <x-warehouse.page-header title="Detail Barang Habis Pakai" subtitle="Identitas master dan saldo terpisah per lokasi serta kondisi."><a class="btn btn-outline-primary" href="{{ route('warehouse.consumables.edit', $consumable) }}">Ubah Master</a><a class="btn btn-outline-secondary" href="{{ route('warehouse.consumables.index') }}">Kembali</a></x-warehouse.page-header>

        <div class="warehouse-detail-grid">
            <x-warehouse.panel title="Informasi barang" class="warehouse-detail-full"><dl class="warehouse-definition-list">
                @if($consumable->photo_path)<dt>Foto</dt><dd><img class="warehouse-master-photo-preview" src="{{ \Illuminate\Support\Facades\Storage::disk(config('warehouse.photos.disk', 'public'))->url($consumable->photo_path) }}" alt="Foto {{ $consumable->item_name }}" width="320" height="220"></dd>@endif
                <dt>Item Code</dt><dd class="font-monospace">{{ $consumable->item_code }}</dd><dt>Nama barang</dt><dd>{{ $consumable->item_name }}</dd><dt>Tipe mesin</dt><dd>{{ $consumable->machine_type ?: '—' }}</dd><dt>Stok total</dt><dd><strong>{{ \App\Services\Warehouse\WarehouseQuantity::display($consumable->current_stock) }} {{ $consumable->unit }}</strong></dd><dt>DS8 — Baru</dt><dd>{{ \App\Services\Warehouse\WarehouseQuantity::display($consumable->availableAt('DS8', \App\Enums\Warehouse\WarehouseItemCondition::NEW)) }}</dd><dt>DS8 — Bekas</dt><dd>{{ \App\Services\Warehouse\WarehouseQuantity::display($consumable->stock_used_ds8) }}</dd><dt>Deltamas — Baru</dt><dd>{{ \App\Services\Warehouse\WarehouseQuantity::display($consumable->availableAt('Deltamas', \App\Enums\Warehouse\WarehouseItemCondition::NEW)) }}</dd><dt>Deltamas — Bekas</dt><dd>{{ \App\Services\Warehouse\WarehouseQuantity::display($consumable->stock_used_deltamas) }}</dd><dt>Stok minimum</dt><dd>{{ \App\Services\Warehouse\WarehouseQuantity::display($consumable->minimum_stock) }}</dd><dt>Stok maksimum</dt><dd>{{ $consumable->maximum_stock !== null ? \App\Services\Warehouse\WarehouseQuantity::display($consumable->maximum_stock) : '—' }}</dd><dt>Lokasi default</dt><dd>{{ $consumable->storage_location ?: '—' }}</dd><dt>Status stok</dt><dd><x-warehouse.status-badge :status="$consumable->stock_status" context="stock" /></dd><dt>Status master</dt><dd><x-warehouse.status-badge :status="$consumable->is_active ? 'ACTIVE' : 'INACTIVE'" context="activity" /></dd>
            </dl></x-warehouse.panel>

            <section class="warehouse-panel warehouse-detail-full" aria-labelledby="warehouse-opening-balance-title"><div class="warehouse-panel-header"><div><h2 id="warehouse-opening-balance-title">Atur saldo awal</h2><p>Saldo awal selalu dicatat sebagai barang Baru dan wajib diverifikasi oleh RAGIL atau ARY.</p></div></div><form method="POST" action="{{ route('warehouse.consumables.opening-balance', $consumable) }}" class="warehouse-panel-body">@csrf<div class="warehouse-detail-grid"><div class="warehouse-form-field"><label class="form-label warehouse-required" for="opening-quantity">Jumlah</label><input class="form-control" id="opening-quantity" name="quantity" type="number" min="1" step="1" inputmode="numeric" required></div><div class="warehouse-form-field"><label class="form-label warehouse-required" for="opening-location">Lokasi</label><select class="form-select" id="opening-location" name="storage_location" required>@foreach(config('warehouse.storage_locations') as $location)<option value="{{ $location }}">{{ $location }}</option>@endforeach</select></div><div class="warehouse-form-field"><label class="form-label warehouse-required" for="opening-code">Pindai barcode NPK verifikator</label><input class="form-control font-monospace" id="opening-code" name="verified_code" inputmode="numeric" autocomplete="off" required></div><div class="warehouse-form-field warehouse-detail-full"><label class="form-label warehouse-required" for="opening-reason">Alasan</label><input class="form-control" id="opening-reason" name="reason" required></div></div><input type="hidden" name="idempotency_key" value="{{ (string) str()->uuid() }}"><button class="btn btn-primary mt-3" type="submit">Catat Saldo Awal</button></form></section>
        </div>
    </div>
@endsection
